### ISSUE TITLE
Update checkout to v4

### ISSUE THREAD

**Issue by jan-abel-inwt** [mikemahoney218/upload-to-drat-repo#2]
Hi there,

First of all, thank you so much for creating this GitHub action! It's been very helpful.

I noticed in the action.yml file that the checkout version is currently set to a previous version. Would it be possible to update it to v4?

Thanks again for your work on this!

**Comment by mikemahoney218** [comment]
Thanks for the report! Version 0.2.1 bumps the checkout action.

**Comment by jan-abel-inwt** [comment]
Thanks
