### ISSUE TITLE
Enhance drat action with `drat::archivePackages` functionality

### ISSUE THREAD

**Issue by jan-abel-inwt** [mikemahoney218/upload-to-drat-repo#3]
Hi again, 

I've noticed that in the drat package, there's a function called `drat::archivePackages` which moves older versions into a CRAN-style archive folder. I believe incorporating this functionality into the action would be beneficial.

To achieve this, could you consider adding the following line to the action's script?

```
R -e `drat::archivePackages(repopath = 'drat')`
```

I think this could effectively replace the current line:

```
R -e 'drat::updateRepo("drat")'
```

What do you think? Should this be an optional feature or included by default?

Thank you once again for your efforts!

**Comment by mikemahoney218** [comment]
Added flags for archive and for prune in v0.3!
